#!/usr/bin/env python3
"""
An internal git wrapper to simplify the handling of submodules.
"""

import sys
from subprocess import run

from xg import find_command, command_help

# Load the command modules to register their commands.
from xg import base, branches, commits, submodules


def main(args) -> int:
    """Main function."""
    if len(args) <= 1:
        command_help()
        return 1
    if (command := find_command(args[1])) is not None:
        try:
            return command(*args[2:])
        except TypeError:
            print("Nombre d'arguments invalide.")
            command_help(args[1])
            return 1
    git = run(["git"] + args[1:])
    return git.returncode


if __name__ == "__main__":
    sys.exit(main(sys.argv))
